import logging
import os

logger = logging.getLogger(__name__)

TILED_INGEST_PIKA_LOG_LEVEL = os.get_env(
    "TILED_INGEST_PIKE_LOG_LEVEL", logging.CRITICAL
)
TILED_INGEST_RMQ_HOST = os.getenv("TILED_INGEST_RMQ_HOST")
TILED_INGEST_RMQ_USER = os.getenv("TILED_INGEST_RMQ_USER")
TILED_INGEST_RMQ_PW = os.getenv("TILED_INGEST_RMQ_PW")

TILED_INGEST_TILED_CONFIG_PATH = os.getenv("TILED_INGEST_TILED_CONFIG_PATH")

logger.info(f"TILED_INGEST_PIKA_LOG_LEVEL  {TILED_INGEST_PIKA_LOG_LEVEL}")
logger.info(f"TILED_INGEST_RMQ_HOST  {TILED_INGEST_RMQ_HOST}")
logger.info(f"TILED_INGEST_RMQ_USER  {TILED_INGEST_RMQ_USER}")
logger.info("TILED_INGEST_RMQ_PW  not logged")
logger.info(f"TILED_INGEST_TILED_CONFIG_PATH  {TILED_INGEST_TILED_CONFIG_PATH}")
